parameters:
    oro_issue.form.type.issue.class:        Oro\Bundle\IssueBundle\Form\Type\IssueType
    oro_issue.form.handler.issue.class:     Oro\Bundle\IssueBundle\Form\Handler\IssueHandler

    oro_issue.form.type.issue_api.class:    Oro\Bundle\IssueBundle\Form\Type\IssueApiType
    oro_issue.form.handler.issue_api.class: Oro\Bundle\IssueBundle\Form\Handler\IssueHandler

services:
    oro_issue.form.type.issue:
        class: %oro_issue.form.type.issue.class%
        tags:
            - { name: form.type, alias: oro_issue_form_issue }

    oro_issue.form.issue:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "oro_issue_form_issue"
            - "oro_issue_form_issue"

    oro_issue.form.handler.issue:
        class: %oro_issue.form.handler.issue.class%
        scope: request
        arguments:
            - @oro_issue.form.issue
            - @request
            - @doctrine.orm.entity_manager
