oro_menu_config:
   items:
       issues_tab:
           label: 'oro.issue.entity_plural_label'
           uri: '#'
           extras:
               position: 50

       issue_list:
           label: 'oro.issue.list_label'
           route: 'oro_issue_index'

   tree:
       application_menu:
           children:
               issues_tab:
                   children:
                       issue_list: ~