parameters:
    oro_issue.entity.issue.class: Oro\Bundle\IssueBundle\Entity\Issue
    oro_issue.from.type.issue_api.class: Oro\Bundle\IssueBundle\Form\Type\IssueApiType
    oro_issue.from.handler.issue_api.class: Oro\Bundle\IssueBundle\Form\Handler\IssueHandler
    oro_issue.note_listener.class: Oro\Bundle\IssueBundle\EventListener\NoteListener
    oro_issue.issue_listener.class: Oro\Bundle\IssueBundle\EventListener\IssueListener

services:
    oro_issue.note_listener:
        class: %oro_issue.note_listener.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    oro_issue.issue_listener:
        class: %oro_issue.issue_listener.class%
        arguments:
            - @oro_entity_config.link.security_context
        tags:
            - { name: doctrine.event_listener, event: postPersist}
            - { name: doctrine.event_listener, event: onFlush}

